services:

  postgres:
    image: postgres:17-alpine
    container_name: ai-task-postgres

    environment:
      POSTGRES_DB: aitaskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aitaskmanager"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: ai-task-manager

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/aitaskmanager
      DB_PASSWORD: ${DB_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    ports:
      - "8080:8080"


volumes:
  postgres_data: